added commit and push to docs workflow

diff --git a/.github/workflows/docs.yaml b/.github/workflows/docs.yaml
--- a/.github/workflows/docs.yaml
+++ b/.github/workflows/docs.yaml
@@ -43,6 +43,7 @@ jobs:
       run: |
         python -m pip install . --no-deps
         conda list
+
     - name: Build Documentation
 
       # conda setup requires this special shell
@@ -50,6 +51,24 @@ jobs:
 
       run: |
         cd docs
-        make clean
         make html
         cd ../
+
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/jonwzheng/molssi-best-practices-workshop.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+        
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
